// SkillScroll backend: zero dependencies, JSON-file database. Works on Node 18+.
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
process.chdir(__dirname);fs.mkdirSync('uploads',{recursive:true});
let env={};try{fs.readFileSync('.env','utf8').split(/\r?\n/).forEach(l=>{const i=l.indexOf('=');if(i>0&&l[0]!=='#')env[l.slice(0,i).trim()]=l.slice(i+1).trim()})}catch{}
const E=k=>process.env[k]||env[k],SECRET=E('SESSION_SECRET')||'dev-secret-change-me',PORT=+E('PORT')||3000;
const FILE='data.json';let db={seq:1,users:[],opps:[],saves:[],journeys:[],teams:[],members:[],msgs:[],refl:[]};
try{db=JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{}
const save=()=>{fs.writeFileSync(FILE+'.tmp',JSON.stringify(db));fs.renameSync(FILE+'.tmp',FILE)};
const DIMS=['analytical','communication','creativity','collaboration','leadership','research','technical'];
const W={mun:['communication','research','leadership'],hack:['technical','creativity','collaboration','analytical'],research:['research','analytical'],volunteer:['collaboration','leadership'],arts:['creativity','communication'],sports:['collaboration','leadership']};
const J={mun:[['Learn MUN basics','Understand committees, delegates, points of order and how a resolution passes.'],['Research your country',"Find your country's stance on the agenda, its allies and past votes."],['Draft a position paper','One page: background, national policy, proposed solutions.'],['Practise a 90-second speech','Open with your country, make one clear ask, close with a call to action.'],['Run a mock committee','Hold a mock caucus with your team and negotiate one clause.']],
hack:[['Identify a real problem','Talk to three people affected. Write the problem in one sentence.'],['Ideate and choose','Sketch five ideas, then pick one using impact and feasibility.'],['Form your team','Cover builder, designer and storyteller roles. Agree how you decide.'],['Build the MVP','Ship one working flow end to end. Cut everything else.'],['Pitch it in 3 minutes','Problem, solution, demo, impact, ask.']],
other:[['Understand the opportunity','Read the brief and note what the organisers value.'],['Set a goal','Decide what you want to gain and how you will show it.'],['Prepare your materials','Gather what you need to apply or participate.'],['Practise','Rehearse with a friend or mentor.'],['Plan your day','Confirm logistics and your team roles.']]};
const steps=t=>J[t]||J.other;
const bad=(s,m)=>{throw{s,m}},str=(v,a,b,n)=>{v=typeof v==='string'?v.trim():'';if(v.length<a||v.length>b)bad(400,`${n} must be ${a}–${b} characters`);return v};
const hash=p=>{const s=crypto.randomBytes(16);return s.toString('hex')+':'+crypto.scryptSync(p,s,64).toString('hex')};
const check=(p,h)=>{const[s,k]=h.split(':');return crypto.timingSafeEqual(crypto.scryptSync(p,Buffer.from(s,'hex'),64),Buffer.from(k,'hex'))};
const sign=d=>d+'.'+crypto.createHmac('sha256',SECRET).update(d).digest('hex');
const verify=t=>{const i=(t||'').lastIndexOf('.');if(i<0)return null;const d=t.slice(0,i);if(sign(d)!==t)return null;const[id,exp]=d.split(':');return +exp>Date.now()?+id:null};
const hits=new Map();const limit=(k,max,ms)=>{const n=Date.now(),h=hits.get(k);if(!h||h[1]<n){hits.set(k,[1,n+ms]);return}if(++h[0]>max)bad(429,'Too many requests. Try again shortly.')};
const pub=u=>({id:u.id,name:u.name,email:u.email,role:u.role,assessed:Object.keys(u.scores||{}).length>0});
const lvl=u=>{const s={...(u.scores||{})};db.refl.filter(r=>r.u===u.id).forEach(r=>r.skills.forEach(k=>s[k]=Math.min(100,(s[k]||0)+10)));return s};
const opp=id=>db.opps.find(o=>o.id===+id),user=id=>db.users.find(u=>u.id===id);
const jr=(u,o)=>db.journeys.find(j=>j.u===u&&j.o===+o),isMem=(t,u)=>db.members.some(m=>m.t===+t&&m.u===u);
const mem=(c,t)=>{if(!isMem(t,c.u.id)||!db.teams.some(x=>x.id===+t))bad(404,'Not found')};
async function gemini(sys,msg){const k=E('GEMINI_API_KEY');if(!k)return null;try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${E('GEMINI_MODEL')||'gemini-2.5-flash'}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':k},body:JSON.stringify({systemInstruction:{parts:[{text:sys}]},contents:[{role:'user',parts:[{text:msg}]}]})});const d=await r.json();return d.candidates?.[0]?.content?.parts?.map(p=>p.text).join('')||null}catch{return null}}
const routes=[];const R=(m,p,role,fn)=>routes.push([m,new RegExp('^'+p+'$'),role,fn]);
const mkUser=(email,name,pw,role)=>{const u={id:db.seq++,email,name,pw:hash(pw),role,scores:{}};db.users.push(u);return u};
R('POST','/api/signup',null,c=>{limit('a'+c.ip,20,6e5);const email=str(c.b.email,5,120,'Email').toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))bad(400,'Enter a valid email');const pw=str(c.b.password,8,100,'Password'),name=str(c.b.name,2,60,'Name');if(db.users.some(u=>u.email===email))bad(409,'Email already registered');const u=mkUser(email,name,pw,c.b.role==='organizer'?'organizer':'student');save();return c.login(u)});
R('POST','/api/login',null,c=>{limit('a'+c.ip,20,6e5);const u=db.users.find(x=>x.email===String(c.b.email||'').toLowerCase());if(!u||!check(String(c.b.password||''),u.pw))bad(401,'Incorrect email or password');return c.login(u)});
R('POST','/api/logout',null,c=>{c.cookie='ss=; Max-Age=0; Path=/';return{ok:1}});
R('GET','/api/me',null,c=>({user:c.u?pub(c.u):null}));
R('POST','/api/assess','student',c=>{const s={};for(const d of DIMS){const v=+c.b[d];if(!(v>=1&&v<=5))bad(400,'Answer every question');s[d]=v*20}c.u.scores=s;save();return{scores:s}});
R('GET','/api/opps','student',c=>db.opps.filter(o=>o.pub).map(o=>({...o,saved:db.saves.some(s=>s.u===c.u.id&&s.o===o.id)})));
R('GET','/api/opps/(\\d+)','student',c=>{const o=opp(c.p[0]);if(!o||!o.pub)bad(404,'Not found');const j=jr(c.u.id,o.id);return{...o,steps:steps(o.type).map(s=>({title:s[0],desc:s[1]})),journey:j?{done:j.done}:null,saved:db.saves.some(s=>s.u===c.u.id&&s.o===o.id),reflection:db.refl.find(r=>r.u===c.u.id&&r.o===o.id)||null,teams:db.teams.filter(t=>t.o===o.id&&isMem(t.id,c.u.id)).map(t=>({id:t.id,name:t.name}))}});
R('POST','/api/opps/(\\d+)/save','student',c=>{const i=db.saves.findIndex(s=>s.u===c.u.id&&s.o===+c.p[0]);i>=0?db.saves.splice(i,1):db.saves.push({u:c.u.id,o:+c.p[0]});save();return{ok:1}});
R('GET','/api/journeys','student',c=>db.journeys.filter(j=>j.u===c.u.id).map(j=>{const o=opp(j.o);return{id:o.id,title:o.title,type:o.type,done:j.done.length,total:steps(o.type).length}}));
R('GET','/api/recommend','student',c=>{const L=lvl(c.u),has=Object.keys(L).length,done=new Set(db.refl.filter(r=>r.u===c.u.id).map(r=>r.o));
return db.opps.filter(o=>o.pub&&!done.has(o.id)).map(o=>{const w=W[o.type]||DIMS,fit=has?Math.round(w.reduce((a,k)=>a+(L[k]||0),0)/w.length):null,top=[...w].sort((a,b)=>(L[b]||0)-(L[a]||0))[0];return{...o,fit,why:has?`Builds on your ${top} strength`:'Take the assessment to personalise'}}).sort((a,b)=>(b.fit||0)-(a.fit||0))});
R('POST','/api/opps/(\\d+)/journey','student',c=>{const o=opp(c.p[0]);if(!o||!o.pub)bad(404,'Not found');if(!jr(c.u.id,o.id))db.journeys.push({u:c.u.id,o:o.id,done:[]});save();return{ok:1}});
R('POST','/api/opps/(\\d+)/step','student',c=>{const o=opp(c.p[0]),j=o&&jr(c.u.id,o.id);if(!j)bad(404,'Start the journey first');const i=+c.b.index;if(!(i>=0&&i<steps(o.type).length))bad(400,'Invalid step');j.done=j.done.includes(i)?j.done.filter(x=>x!==i):[...j.done,i];save();return{done:j.done}});
R('POST','/api/teams','student',c=>{if(!jr(c.u.id,+c.b.oppId))bad(400,'Start the journey first');const t={id:db.seq++,o:+c.b.oppId,name:str(c.b.name,2,50,'Team name'),code:crypto.randomBytes(3).toString('hex').toUpperCase()};db.teams.push(t);db.members.push({t:t.id,u:c.u.id});save();return{id:t.id}});
R('POST','/api/teams/join','student',c=>{limit('j'+c.u.id,10,6e4);const t=db.teams.find(x=>x.code===String(c.b.code||'').trim().toUpperCase());if(!t)bad(404,'No team with that code');if(!isMem(t.id,c.u.id))db.members.push({t:t.id,u:c.u.id});save();return{id:t.id}});
R('GET','/api/teams/(\\d+)','student',c=>{mem(c,c.p[0]);const t=db.teams.find(x=>x.id===+c.p[0]),o=opp(t.o);return{...t,opp:{id:o.id,title:o.title},members:db.members.filter(m=>m.t===t.id).map(m=>({name:user(m.u).name})),msgs:db.msgs.filter(m=>m.t===t.id).slice(-100).map(m=>({id:m.id,body:m.body,ts:m.ts,name:user(m.u).name}))}});
R('POST','/api/teams/(\\d+)/msgs','student',c=>{mem(c,c.p[0]);limit('m'+c.u.id,30,6e4);db.msgs.push({id:db.seq++,t:+c.p[0],u:c.u.id,body:str(c.b.body,1,1000,'Message'),ts:Date.now()});save();return{ok:1}});
R('POST','/api/ai','student',async c=>{limit('ai'+c.u.id,20,6e4);const o=opp(c.b.oppId);if(!o)bad(404,'Not found');const msg=str(c.b.message,1,800,'Message'),S=steps(o.type),j=jr(c.u.id,o.id),done=j?j.done:[],next=S.findIndex((_,i)=>!done.includes(i));
const tm=db.teams.find(t=>t.o===o.id&&isMem(t.id,c.u.id));let team='No team yet.';if(tm)team=`Team "${tm.name}". Recent messages: `+db.msgs.filter(m=>m.t===tm.id).slice(-8).map(m=>`${user(m.u).name}: ${m.body}`).join(' | ');
const sys=`You are SkillScroll's coach. Be warm, concrete, under 120 words. Student: ${c.u.name}. Skills (0-100): ${JSON.stringify(lvl(c.u))}. Opportunity: ${o.title} (${o.type}). Stage: ${next<0?'preparation complete, ready to reflect':`step ${next+1}/${S.length}: ${S[next][0]}`}. ${team}`;
const a=await gemini(sys,msg);return{reply:a||(next<0?'Preparation is done. Write a reflection on your role and evidence.':`Focus on "${S[next][0]}". ${S[next][1]} Share a draft and I will give feedback.`)}});
R('POST','/api/reflect','student',c=>{const o=opp(c.b.oppId),j=o&&jr(c.u.id,o.id);if(!j||j.done.length<steps(o.type).length)bad(400,'Complete every preparation step first');const sk=[...new Set(c.b.skills)].filter(k=>DIMS.includes(k));if(!sk.length)bad(400,'Pick at least one demonstrated skill');
db.refl=db.refl.filter(r=>!(r.u===c.u.id&&r.o===o.id));db.refl.push({u:c.u.id,o:o.id,role:str(c.b.role,2,60,'Role'),text:str(c.b.text,20,2000,'Reflection'),skills:sk,evidence:str(c.b.evidence,3,500,'Evidence'),ts:Date.now()});save();return{ok:1}});
R('GET','/api/passport','student',c=>({scores:lvl(c.u),base:c.u.scores,entries:db.refl.filter(r=>r.u===c.u.id).sort((a,b)=>b.ts-a.ts).map(r=>({...r,title:opp(r.o).title}))}));
R('GET','/api/org/opps','organizer',c=>db.opps.filter(o=>o.org===c.u.id).map(o=>({...o,teams:db.teams.filter(t=>t.o===o.id).map(t=>({id:t.id,name:t.name,code:t.code,members:db.members.filter(m=>m.t===t.id).map(m=>({name:user(m.u).name,email:user(m.u).email}))}))})));
const oppIn=b=>({title:str(b.title,3,100,'Title'),type:W[b.type]?b.type:bad(400,'Invalid type'),summary:str(b.summary,10,600,'Summary'),date:str(b.date,4,40,'Date'),hue:Math.max(0,Math.min(360,+b.hue||210)),pub:b.pub?1:0});
R('POST','/api/org/opps','organizer',c=>{const o={id:db.seq++,org:c.u.id,image:null,...oppIn(c.b)};db.opps.push(o);save();return{id:o.id}});
R('PUT','/api/org/opps/(\\d+)','organizer',c=>{const o=opp(c.p[0]);if(!o||o.org!==c.u.id)bad(404,'Not found');Object.assign(o,oppIn(c.b));save();return{ok:1}});
const MAGIC={png:[0x89,0x50,0x4e,0x47],jpg:[0xff,0xd8,0xff],webp:[0x52,0x49,0x46,0x46]};
R('POST','/api/org/opps/(\\d+)/image','organizer',c=>{const o=opp(c.p[0]);if(!o||o.org!==c.u.id)bad(404,'Not found');const m=/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/.exec(c.b.data||'');if(!m)bad(400,'Use a PNG, JPG or WebP image');const buf=Buffer.from(m[2],'base64');if(buf.length>2*1024*1024)bad(413,'Image must be under 2 MB');const ext=Object.keys(MAGIC).find(e=>MAGIC[e].every((v,i)=>buf[i]===v));if(!ext)bad(400,'File content is not a valid image');const f=crypto.randomBytes(12).toString('hex')+'.'+ext;fs.writeFileSync(path.join('uploads',f),buf);o.image=f;save();return{image:f}});
if(!db.users.length){const o=mkUser('org@skillscroll.dev','Himalaya OC','Skillscroll1!','organizer');mkUser('demo@skillscroll.dev',' Demo','Skillscroll1!','student');
[['Kathmandu Model UN 2026','mun','Three days of diplomacy. Represent a nation, negotiate resolutions and find your voice in committee.','Nov 14–16',255],['Himalayan Hack Day','hack','A 24-hour build sprint on civic technology. Form a team, ship an MVP, pitch to mentors.','Dec 6–7',190],['Youth Climate Research Fellowship','research','Eight weeks of guided research on mountain ecosystems, ending in a published student brief.','Applications close Nov 30',150],['Riverside Clean-up Drive','volunteer','Lead a crew restoring a stretch of the Bagmati. Build teams and measure impact.','Oct 25',30]].forEach(([title,type,summary,date,hue])=>db.opps.push({id:db.seq++,org:o.id,title,type,summary,date,hue,image:null,pub:1}));save()}
const MIME={png:'image/png',jpg:'image/jpeg',webp:'image/webp'};
http.createServer(async(req,res)=>{const send=(s,b,h={})=>{res.writeHead(s,{'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',...h});res.end(b)};
try{const url=new URL(req.url,'http://x'),ip=req.socket.remoteAddress;
if(req.method==='GET'&&!url.pathname.startsWith('/api')){if(url.pathname.startsWith('/uploads/')){const f=path.basename(url.pathname),e=f.split('.').pop();if(!MIME[e]||!fs.existsSync('uploads/'+f))return send(404,'');return send(200,fs.readFileSync('uploads/'+f),{'Content-Type':MIME[e]})}return send(200,fs.readFileSync('public/index.html'),{'Content-Type':'text/html; charset=utf-8'})}
const ck={};(req.headers.cookie||'').split(';').forEach(s=>{const i=s.indexOf('=');if(i>0)ck[s.slice(0,i).trim()]=s.slice(i+1).trim()});const uid=verify(ck.ss);
const c={ip,u:uid?user(uid):null,b:{},cookie:null,login(u){c.cookie=`ss=${sign(u.id+':'+(Date.now()+6048e5))}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800`;return{user:pub(u)}}};
if(req.method!=='GET'){let n=0,ch=[];for await(const x of req){n+=x.length;if(n>3e6)bad(413,'Too large');ch.push(x)}try{c.b=JSON.parse(Buffer.concat(ch).toString()||'{}')}catch{bad(400,'Invalid JSON')}}
for(const[m,re,role,fn]of routes){const mm=re.exec(url.pathname);if(m!==req.method||!mm)continue;c.p=mm.slice(1);if(role){if(!c.u)bad(401,'Please sign in');if(c.u.role!==role)bad(403,'Not allowed for your account type')}const out=await fn(c);return send(200,JSON.stringify(out),{'Content-Type':'application/json',...(c.cookie?{'Set-Cookie':c.cookie}:{})})}
bad(404,'Not found')}catch(e){console.error(e.s?e.m:e);send(e.s||500,JSON.stringify({error:e.m||'Server error'}),{'Content-Type':'application/json'})}}).listen(PORT,()=>console.log('SkillScroll running: http://localhost:'+PORT));
